### ISSUE TITLE
skip comments in file

### ISSUE THREAD

**Issue by sanjeevtripurari** [haginara/sshpt#1]
Hi, i have file list, with comments
but  hostfile (-f), considers all entries as hostnames.

i made change should i give you the pull request

**Comment by sanjeevtripurari** [comment]
./sshpt.py -u sanjeevt  -f staging "hostname; date"
Password: 

Connecting failed (for whatever reason)
"#min1004.myhosts.at.home","FAILED","2015-10-27 12:50:59.901991","hostname; date","[Errno 8] nodename nor servname provided, or not known"
"min1001.myhosts.at.home","SUCCESS","2015-10-27 12:51:01.961716","hostname; date","min1001.myhosts.at.home
Tue Oct 27 07:20:59 UTC 2015"
"min1003.myhosts.at.home","SUCCESS","2015-10-27 12:51:01.961828","hostname; date","min1003.myhosts.at.home
Tue Oct 27 07:20:59 UTC 2015"

**Comment by sanjeevtripurari** [comment]
./sshpt.py -u sanjeevt -f staging "hostname; date"
Password:

Connecting failed (for whatever reason)
"#min1004.myhosts.at.home","FAILED","2015-10-27 12:50:59.901991","hostname; date","[Errno 8] nodename nor servname provided, or not known"
"min1001.myhosts.at.home","SUCCESS","2015-10-27 12:51:01.961716","hostname; date","min1001.myhosts.at.home
Tue Oct 27 07:20:59 UTC 2015"
"min1003.myhosts.at.home","SUCCESS","2015-10-27 12:51:01.961828","hostname; date","min1003.myhosts.at.home
Tue Oct 27 07:20:59 UTC 2015"

**Comment by sanjeevtripurari** [comment]
my local, hostfile: staging

min1001.myhosts.at.home

min1002.myhosts.at.home
min1003.myhosts.at.home
#min1004.myhosts.at.home
min1005.myhosts.at.home

**Comment by haginara** [comment]
I think that is a good enhancements. please go ahead.
